name: Flutter_Tests

on:
  push:
    branches: [master, development, feature_action_test] #Testing in this branch
  pull_request:
    branches: [master, development]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: 'stable'
      - name: Check status
        run: flutter foctor
      - name: Update pub
        run: flutter pub upgrade
      - name: Restore packages
        run: flutter pub get
        
      - name: Run Tests
        run: flutter test
        
